### ISSUE TITLE
options of processing non full-frame pictures

### ISSUE THREAD

**Issue by simblanco** [GastonMauroDiaz/caiman#1]
Hello, I am using this package to process HP images and I am really pleased with the result. I have non-fullframe pictures (see attached example, the HP image is not contained in a square) but it is not possible to process them. Any solution? Thanks
![a307-2](https://cloud.githubusercontent.com/assets/519816/16408941/004beb86-3d13-11e6-805c-af0b2a07be22.jpg)

**Comment by GastonMauroDiaz** [comment]
Hello, is good to know that the package has been useful for you.

Your example picture is full-frame (the rectangular one in which all the pixels have some data). The non-full-frame are the traditional circular pictures. There is a very good figure showing this in the paper of Schneider et al. (2009) (http://www.sciencedirect.com/science/article/pii/S0924271609000045).

I added your requested feature in the new version of the package. I processed your example and attached the result. The first was processed with enhanceHemiPhoto() and the second with doOBIA().

Please, see the documentation of the functions for more details. Let me know if you need additional help to process this kind of image.

![fullframe_bin_enhancehemiphoto](https://cloud.githubusercontent.com/assets/9575430/16620174/d105be0a-4367-11e6-9b5e-07910c6f9dd7.jpg)

![fullframe_doobia](https://cloud.githubusercontent.com/assets/9575430/16620201/f4d009da-4367-11e6-9015-874b9dc73c3f.jpg)

**Comment by simblanco** [comment]
Thanks for your help! I am eventually now able to work more on this issue and reply.

First of all, thanks for the clarification about terminology. I think there was some confusion between "full format" hemispherical photos and "full-frame" cameras (I referred to cameras with a 35mm sensor format like the old film). I like much better the terms "circular" and "diagonal" hemiphoto. So I reckon the pic in the example is a "diagonal" one.

I managed to replicate your example with enhanceHemiPhoto:

```
x <- loadPhoto("github.JPG", upperLeft = c(1,1), width = 3263, height = 1835)
fisheye(x) <- newFishEye(T, T, T)
x <- normalize(x, 0, 255)
m <- enhanceHemiPhoto(x)
writeRaster(autoThr(m)*255, "github_enhanced.TIF", datatype = "INT1U", overwrite = TRUE)
```

However, if I test the OBIA function:

```
x <- loadPhoto("github.JPG", upperLeft = c(1,1), width = 3263, height = 1835)
fisheye(x) <- newFishEye(T, T, T)
x <- normalize(x, 0, 255)
z <- makeZimage(ncol(x), lensPolyCoef())
seg <- doPolarQtree(x, z, scaleParameter = 1)
out <- doOBIA(x, z, seg, zlim = asAngle(c(20, 80)))
writeRaster(out * 255, `"github_obia.tif",` datatype = "INT1U", overwrite = TRUE)
```

when executing the doPolarQtree step I get this error message (regardless of the scaleParameter used:

> Error in doPolarQtree(x, z, scaleParameter = 1) : 
>   Maybe you not declare your hemispherical photo as a fullframe. To do it, use fisheye(x) <- newFishEye(TRUE, TRUE, TRUE), for example.

I am using the latest version of Caiman (from devtools::install_github("GastonMauroDiaz/caiman") on R version 3.3.1

The function enhanceHemiPhoto gives results already better than the autothreshold Isodata method from FIJI/ImageJ, but I'd like to compare it with the OBIA if possible. Other than many "diagonal" hemiphotos taken with non-fullframe cameras (?!) I am using a old Nikon Coolpix 990 that systemically cut a bit of the image in the lower part. Thanks!!

EDIT: ok, the problem with the Nikon Coolpix 990 is not the same and I found already some workarounds

**Comment by GastonMauroDiaz** [comment]
Hello, 
The current version of caiman could do the job but you need to change the script. Please, use this:

```
setwd("c:/users/gdiaz/downloads")
x <- loadPhoto("github.JPG", upperLeft = c(1,1), width = 3263, height = 1835)
fisheye(x) <- newFishEye(T, T, T)
x <- normalize(x, 0, 255)
z <- makeZimage(ncol(expandFullframe(x)), lensPolyCoef())
seg <- doPolarQtree(x, z, scaleParameter = 0.5)
out <- doOBIA(x, z, seg, zlim = asAngle(c(20, 80)))
writeRaster(out * 255, `"github_obia.tif",` datatype = "INT1U", overwrite = TRUE)
```

I need to improve the documentation because it is anything but clear in that issue. Also,  I think that you are right about the confusion around the "full frame" terminology  and in a future release I will change "fullframe" for "diagonal" in the documentation and code.

Please let me know if your problem was solved. 
Bye.

**Comment by GastonMauroDiaz** [comment]
Hello simblanco, I closed this issue but you can open a new one if you need some help.
